MODULE FJEM_MATHS_CONSTANTS
  use FJEM_Base
  implicit none
  private
  public pi_, e_

  REAL(KIND=FJEMP), PARAMETER :: pi_ = 4.0_FJEMP * ATAN(1.0_FJEMP)
  REAL(KIND=FJEMP), PARAMETER :: e_ = EXP(1.0_FJEMP)

END MODULE FJEM_MATHS_CONSTANTS
